# -*- coding: utf-8 -*-
"""07.07.02 Exercícios Listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BA-7w6uZza1l-gkiU_nn-K0VJ6n-aoFQ

# Exercícios

## 1. Faturamento do Melhor e do Pior Mês do Ano

Qual foi o valor de vendas do melhor mês do Ano?
E valor do pior mês do ano?
"""
'''
meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
vendas_1sem = [25000, 29000, 22200, 17750, 15870, 19900]
vendas_2sem = [19850, 20120, 17540, 15555, 49051, 9650]

vendas_ano = vendas_1sem + vendas_2sem
i_melhor = vendas_ano.index(max(vendas_ano))
i_pior = vendas_ano.index(min(vendas_ano))
print(f'Melhor Mês do ano: {meses[i_melhor]} - {max(vendas_ano)}')
print(f'Pior Mês do ano: {meses[i_pior]} - {min(vendas_ano)}')
'''

"""## 2. Continuação

Agora relacione as duas listas para printar 'O melhor mês do ano foi {} com {} vendas' 
e o mesmo para o pior mês do ano.

Calcule também o faturamento total do Ano e quanto que o melhor mês representou do 
faturamento total.

Obs: Para o faturamento total, pode usar a função sum(lista) que soma todos os itens de uma lista
"""
meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
vendas_1sem = [25000, 29000, 22200, 17750, 15870, 19900]
vendas_2sem = [19850, 20120, 17540, 15555, 49051, 9650]

vendas_ano = vendas_1sem + vendas_2sem
melhor = max(vendas_ano)
pior = min(vendas_ano)
i_melhor = vendas_ano.index(max(vendas_ano))
i_pior = vendas_ano.index(min(vendas_ano))
fat_ano = sum(vendas_ano)
print(f'O melhor mês do ano foi {meses[i_melhor]} com {melhor} vendas')
print(f'O pior mês do ano foi {meses[i_pior]} com {pior} vendas')
print(f'Faturamento total do ano: {fat_ano}')
print(f'Porcentagem representante do melhor mês: {((melhor / fat_ano) * 100):.2f}%')


"""## 3. Crie uma lista com o top 3 valores de vendas do ano (sem fazer "no olho")

Dica: o método remove retira um item da lista.
"""

top3 = []

for i in range(3):
    top3.append(vendas_ano.pop(vendas_ano.index(max(vendas_ano))))
print(f'Top 3 melhores vendas do ano: {top3}')
